In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd

# Importing the dataset

In [3]:
data = pd.read_csv("C:\\Users\\acer\\Downloads\\archive\\weatherHistory.csv")

In [4]:
data.head()

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.

In [5]:
data.shape

(89999, 11)

# Preparing Data for training the model

In [6]:
data['Humidity'].value_counts()

0.93    5340
0.92    3658
0.96    3604
0.89    2669
1.00    2620
        ...
0.15      10
0.16       8
0.14       4
0.13       1
0.12       1
Name: Humidity, Length: 90, dtype: int64

In [7]:
# Removing variable which wont have much impact on the prediction
data.drop(['Daily Summary','Loud Cover','Wind Bearing (degrees)'],axis=1,inplace=True)

In [8]:
data

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
0,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,15.8263,1015.13
1,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,15.8263,1015.63
2,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,14.9569,1015.94
3,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,15.8263,1016.41
4,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,15.8263,1016.51
...,...,...,...,...,...,...,...,...
89994,Overcast,rain,5.955556,3.038889,0.83,14.3290,14.9086,997.89
89995,Overcast,rain,5.711111,3.294444,0.84,11.1251,14.1680,998.46
89996,Mostly Cloudy,rain,4.772222,1.716667,0.90,13.5884,14.9086,998.93
89997,Partly Cloudy,rain,3.194444,1.544444,0.96,6.3595,9.8532,998.56
89998,Mostly Cloudy,rain,2.183333,-0.822222,0.96,10.5777,8.3076,998.78

In [9]:
data.shape

(89999, 8)

In [10]:
data.isnull().sum()

Summary                       0
Precip Type                 143
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Visibility (km)               0
Pressure (millibars)          0
dtype: int64

In [11]:
data['Precip Type'].value_counts()

rain    79603
snow    10253
Name: Precip Type, dtype: int64

In [12]:
data['Precip Type'].fillna(method='ffill',inplace=True,axis=0)

In [13]:
data['Precip Type'].value_counts()

rain    79746
snow    10253
Name: Precip Type, dtype: int64

# Converting categorical data into numerical data

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Precip Type']=le.fit_transform(data['Precip Type'])
data['Summary']=le.fit_transform(data['Summary'])

In [15]:
data

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
0,19,0,9.472222,7.388889,0.89,14.1197,15.8263,1015.13
1,19,0,9.355556,7.227778,0.86,14.2646,15.8263,1015.63
2,17,0,9.377778,9.377778,0.89,3.9284,14.9569,1015.94
3,19,0,8.288889,5.944444,0.83,14.1036,15.8263,1016.41
4,17,0,8.755556,6.977778,0.83,11.0446,15.8263,1016.51
...,...,...,...,...,...,...,...,...
89994,18,0,5.955556,3.038889,0.83,14.3290,14.9086,997.89
89995,18,0,5.711111,3.294444,0.84,11.1251,14.1680,998.46
89996,17,0,4.772222,1.716667,0.90,13.5884,14.9086,998.93
89997,19,0,3.194444,1.544444,0.96,6.3595,9.8532,998.56
89998,17,0,2.183333,-0.822222,0.96,10.5777,8.3076,998.78

In [16]:
y=data.iloc[:,0] #Dependent Variable

In [17]:
x = data.iloc[:,1:] #Independent variable

In [18]:
x.corr()  #checking correlation to drop unnecessary variable

,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
Precip Type,1.000000,-0.567672,-0.570158,0.239431,-0.071101,-0.324182,0.009499
Temperature (C),-0.567672,1.000000,0.992545,-0.633583,0.012059,0.391344,-0.005401
Apparent Temperature (C),-0.570158,0.992545,1.000000,-0.603649,-0.054444,0.380201,-0.000021
Humidity,0.239431,-0.633583,-0.603649,1.000000,-0.226718,-0.367396,0.005065
Wind Speed (km/h),-0.071101,0.012059,-0.054444,-0.226718,1.000000,0.107510,-0.049800
Visibility (km),-0.324182,0.391344,0.380201,-0.367396,0.107510,1.000000,0.060925
Pressure (millibars),0.009499,-0.005401,-0.000021,0.005065,-0.049800,0.060925,1.000000

In [19]:
# Apparent Temperature and Temperax.drop
# Apparent Temperature and Temperax.drop
x.drop('Apparent Temperature (C)',axis=1,inplace=True)

In [20]:
x

,Precip Type,Temperature (C),Humidity,Wind Speed (km/h),Visibility (km),Pressure (millibars)
0,0,9.472222,0.89,14.1197,15.8263,1015.13
1,0,9.355556,0.86,14.2646,15.8263,1015.63
2,0,9.377778,0.89,3.9284,14.9569,1015.94
3,0,8.288889,0.83,14.1036,15.8263,1016.41
4,0,8.755556,0.83,11.0446,15.8263,1016.51
...,...,...,...,...,...,...
89994,0,5.955556,0.83,14.3290,14.9086,997.89
89995,0,5.711111,0.84,11.1251,14.1680,998.46
89996,0,4.772222,0.90,13.5884,14.9086,998.93
89997,0,3.194444,0.96,6.3595,9.8532,998.56
89998,0,2.183333,0.96,10.5777,8.3076,998.78

In [21]:
x.shape

(89999, 6)

In [22]:
# Splitting the dataset into train data and test data
# Train dataset is 70% of and Test dataset is 30% of original dataset
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [23]:
x_train.shape

(62999, 6)

In [24]:
x_test.shape

(27000, 6)

# Training The Data

In [25]:
# Using Random Forest Classifier algorithm to predict the weather
# Training model on test data
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(max_depth=32,n_estimators=120,random_state=1)
RF.fit(x_train,y_train)
y_pred = RF.predict(x_test)

# Measuring Accuracy

In [26]:
# Finding accuracy of model using test data
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.56

In [27]:
# To see importance of each variable in prediction
RF.feature_importances_

array([0.00590134, 0.20435143, 0.1523031 , 0.19813119, 0.23251339,
       0.20679955])